name: test_2bit_6bit
default_w_bits: 4
per_layer_bits:
  # Test 2bit support
  transformer.h.0.attn.c_attn: 2
  transformer.h.0.attn.c_proj: 2
  
  # Test 6bit support  
  transformer.h.1.attn.c_attn: 6
  transformer.h.1.attn.c_proj: 6
  
  # Mix with existing bits
  transformer.h.2.attn.c_attn: 4
  transformer.h.2.attn.c_proj: 8
